//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SealTeam6.DataProvider
{
    using System;
    using System.Collections.Generic;
    
    public partial class Connection
    {
        public int ConnectionID { get; set; }
        public string Uri { get; set; }
        public string UserID { get; set; }
        public string Password { get; set; }
        public string Directory { get; set; }
    }
}
