//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SealTeam6.DataProvider
{
    using System;
    using System.Collections.Generic;
    
    public partial class LogHistory
    {
        public int LogHistoryID { get; set; }
        public string LogType { get; set; }
        public string LogSummary { get; set; }
        public string LogDescription { get; set; }
        public System.DateTime Timestamp { get; set; }
    }
}
